### PR TITLE
Graduation Year update visual bug

### LINKED ISSUE #180: Can't edit graduation year on portal

### PR DESCRIPTION
**Pull request by StormFireFox1**
Closes #180.

Adds state set for ProfileUpdate component to reflect client-side change, as well as changing properties of component.

### CODE REVIEW

**Comment by leestanley** [comment]
This component needs some restructuring overall because there's functionality that can be pulled into the containers or the util.js - I'll do a code review at midnight

File: src/components/ProfileUpdate/index.jsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ const ProfileUpdate = props => {
       });
   };
   useEffect(() => {
-    let keys = ['firstName', 'lastName', 'major', 'bio'];
+    let keys = ['firstName', 'lastName', 'major', 'bio', 'graduationYear'];
```
Comment (leestanley) [inline src/components/ProfileUpdate/index.jsx:65]: Is there a reason why this is a let vs. a const?

File: src/components/ProfileUpdate/index.jsx [hunk 2]
```diff
@@ -142,8 +142,14 @@ const ProfileUpdate = props => {
...
                 className="year"
-                onBlur={value => props.setFieldValue('graduationYear', value)}
-                onChange={value => props.setFieldValue('graduationYear', value)}>
+                onBlur={value => {
+                  setGradYear(value);
+                  props.setFieldValue('graduationYear', value);
+                }}
+                onChange={value => {
+                  setGradYear(value);
+                  props.setFieldValue('graduationYear', value);
```
Comment (leestanley) [inline src/components/ProfileUpdate/index.jsx:151]: This should be abstracted to the container with Formik, you can just follow the structure here in the container 
https://github.com/acmucsd/membership-portal-ui/blob/master/src/containers/ProfileUpdate.jsx. If you take a look at other input fields its these functions are passed down as prop as well. Typically we want to remove using anonymous functions within the jsx itself and pass these down as props or defined before the return. 

If you want to take a look at another example here is the container for RegisterForm https://github.com/acmucsd/membership-portal-ui/blob/master/src/containers/RegisterForm.jsx and the component here https://github.com/acmucsd/membership-portal-ui/blob/master/src/components/RegisterForm/index.jsx

File: src/components/ProfileUpdate/index.jsx (hunk 1 above)
Comment (leestanley) [reply src/components/ProfileUpdate/index.jsx:65]: Where is the prop type for grad year 
image

File: src/components/ProfileUpdate/index.jsx (hunk 2 above)
Comment (StormFireFox1) [reply src/components/ProfileUpdate/index.jsx:189]: ReisterForm also uses anonymous functions in the JSX, I assume you'd want both forms to have the funcs moved?

Comment (leestanley) [reply src/components/ProfileUpdate/index.jsx:189]: Yea same should be done with register but we can worry about profile update for now

Comment (StormFireFox1) [reply src/components/ProfileUpdate/index.jsx:155]: I've looked around, and Formik apparently cannot properly deal with Ant Design's selector. Turns out the idiomatic way to create custom Formik change handlers is to write them inline in the JSX, modifying props in the process.

I'll kick this can to the new review I requested.

File: src/components/ProfileUpdate/index.jsx [hunk 3]
```diff
@@ -71,13 +58,10 @@ const ProfileUpdate = (props) => {
       });
   };
   useEffect(() => {
-    const keys = ['firstName', 'lastName', 'major', 'bio'];
+    const keys = ['firstName', 'lastName', 'major', 'bio', 'graduationYear'];
     keys.forEach((key) => {
-      setFieldValue(key, user.profile[key]);
+      props.setFieldValue(key, props.user.profile[key]);
```
Comment (leestanley) [inline src/components/ProfileUpdate/index.jsx:63]: For props you can just use the destructuring above for and replace ```props.setFieldValue``` with ```setFieldValue```. You also don't need to call props for ```props.user.profile``` because it already destructured in ```const { handleBlur, handleChange, handleSubmit, user, values } = props;```

File: src/components/ProfileUpdate/index.jsx [hunk 4]
```diff
@@ -161,10 +145,15 @@ const ProfileUpdate = (props) => {
...
               <Select
-                value={gradYear}
+                name="graduationYear"
+                value={values.graduationYear}
                 className="year"
-                onBlur={(value) => setFieldValue('graduationYear', value)}
-                onChange={(value) => setFieldValue('graduationYear', value)}
+                onBlur={(value) => {
+                  props.setFieldValue('graduationYear', value);
+                }}
```
Comment (leestanley) [inline src/components/ProfileUpdate/index.jsx:153]: Same here

File: src/components/ProfileUpdate/index.jsx [hunk 5]
```diff
@@ -161,10 +145,15 @@ const ProfileUpdate = (props) => {
...
+                onChange={(value) => {
+                  props.setFieldValue('graduationYear', value);
```
Comment (leestanley) [inline src/components/ProfileUpdate/index.jsx:155]: Same here

File: src/components/ProfileUpdate/index.jsx (hunk 3 above)
Comment (StormFireFox1) [reply src/components/ProfileUpdate/index.jsx]: Resolved in 1fdcbdf.

File: src/components/ProfileUpdate/index.jsx (hunk 5 above)
Comment (StormFireFox1) [reply src/components/ProfileUpdate/index.jsx]: Resolved in 1fdcbdf.
